language: ruby

rvm:
        - 2.6.1

addons:
        postgresql: '9.6'

notifications:
        email: false

env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - CC_TEST_REPORTER_ID=3b48e9b8833fb4f2c4224b8615190072110fb0085c6af3ff5f470ad61787f460

before_install: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.6
        - psql -c 'CREATE DATABASE sijrslac_pru;' -U postgres
        - gem install bundler
        - gem update --system
        - bundle update --bundler
        - bundle install
        - cp config/database.travis.yml config/database.yml
        - cp config/initializers/sip.rb.plantilla config/initializers/sip.rb
        - cp config/application.rb.plantilla config/application.rb
        - cp db/structure.sql db/structure.sql.copia # travis no soporta PostreSQL 10
        - sed -e 's/provider = libc,//g' db/structure.sql.copia > db/structure.sql 
        - bundle exec rake db:setup
        - bundle exec rake sip:indices

script: 
        - bundle exec rails test

after_script:
        - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT

